# Generated by Django 6.0.7 on 2026-07-21 23:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.PositiveIntegerField(unique=True)),
                ("truckstop_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.PositiveIntegerField(blank=True, null=True)),
                ("retail_price", models.DecimalField(decimal_places=3, max_digits=5)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["retail_price"],
                "indexes": [
                    models.Index(
                        fields=["city", "state"], name="fuel_fuelst_city_434708_idx"
                    ),
                    models.Index(
                        fields=["retail_price"], name="fuel_fuelst_retail__3784a3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                (
                    "route",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True, srid=4326
                    ),
                ),
                ("distance_miles", models.FloatField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("start", "destination"), name="unique_cached_route"
                    )
                ],
            },
        ),
    ]
